### ISSUE TITLE
fennel is not "lightweight"

### ISSUE THREAD

**Issue by bdsomer** [LordEidi/fennel.js#21]
See [this](http://npm.anvaka.com/#/view/2d/fennel).

The description in your `package.json` file is: "Fennel is a **lightweight** CardDAV / CalDAV server". Doesn't look very lightweight to me.

Some ideas to help this get moving:
- Switch from [`SQL`](https://en.wikipedia.org/wiki/SQL) to [`MongoDB`](https://www.mongodb.com)
- Get [this PR](https://github.com/remy/nodemon/pull/1083) merged (removes [`request`](https://npmjs.com/package/request))

This will remove the following dependencies:
- [`sequelize-sqlite`](https://npmjs.com/package/sequelize-sqlite)
- [`sequelize`](https://npmjs.com/package/sequelize)
- [`sqlite3`](https://npmjs.com/package/sqlite3)

Which will cause an exponential removal of dependencies, as those removed dependencies will remove dependencies that they depend on, which will remove dependencies that the depend on, etc.

The main dependency that will be indirectly removed is [`request`](https://npmjs.com/package/request) as it is [very large](http://npm.anvaka.com/#/view/2d/request).

I really want to use [`fennel`](https://npmjs.com/package/fennel) as a CalDAV server, but with this many dependencies, I can't say yes.

**Comment by Extarys** [comment]
I'm working on a implementation or RethinkDB - If I got some time after that I'll add mongodb ;)

**Comment by bdsomer** [comment]
@Extarys Sounds awesome! And I'd highly recommend using the official MongoDB Node.js driver, [mongodb](https://npmjs.com/package/mongodb). It has less dependencies than [mongoose](https://npmjs.com/package/mongoose), anyway.

A great tool for viewing dependency trees is https://npm.anvaka.com

I highly recommend you use it to cut down on dependencies for faster install times (and faster performance in general). It is worth noting that less disk space is used as well.

I really like this server, and I'll be waiting for this dependency cut! It would also be cool if you exposed an API to developers for events like "eventAdded" and allow developers to handle what happens when calendar events are requested, added, deleted, etc. on top of the functioning server.

I hope this helps, and I can't wait to use this library! Good luck!

**Comment by Extarys** [comment]
Thanks @bdsomer I didn't know about anvaka, very useful!

I'm currently working on two three implementations on different project, I cannot give you any estimation but I'll do what I can.

I'll try to make a db_mysql.js, db_mongodb.js file etc with specific functions in each and the server will just call those functions so you will be able to implement whatever you wish. :)

**Comment by bdsomer** [comment]
@Extarys sounds good!

**Comment by LordEidi** [comment]
@bdsomer, I really understand the point you make. But IMHO you choose the wrong direction to solve the problem. Let me explain.

When starting with Fennel, I stood back and thought hard about SQL vs. NoSQL for storage. I chose SQL back then. While Fennel could be done with NoSQL, I haven't seen an argument yet which would make NoSQL the better decision for storing calendar and address information.

Fennel is using the concept of [ORM](https://en.wikipedia.org/wiki/Object-relational_mapping) to store and access data. Mostly because writing SQL is calling for security trouble and because with a solid ORM you are able to switch database products without too much pain. Back then I looked into Sequelize and Waterline. I chose Sequelize, because Waterline was not working without the framework it came from (that probably changed since then) and it looked quite solid.

Which brings me to your initial comment. Removing SQL and moving to NoSQL because obviously the component Sequelize has somewhat a problem with dependency bloat is not a clever move from an engineering perspective. We would rip out one concept of storing data and move to another concept (without real technical need to do so).

What we should do instead is talking about if it would make sense to remove Sequelize and replace it with something sleeker. We could look at Bookshelf, knex-orm, whatever is out there. I am open for suggestions and comments on that.

Oh and @Extarys. Your comment regarding doing some wrappers around different DB engines. This is what an ORM is there for and what Sequelize actually does (for SQL based DBs). There are already tons of ORM for JavaScript. I am not sure it makes sense to reinvent the wheel there...

**Comment by Extarys** [comment]
Sequelize doesnt support RethinkDB nor MongoDB :(

**Comment by levous** [comment]
I thought I'd resurrect this thread...  I am considering the same thing.  I've added CardDAV as a feature story to my project backlog and referenced this project as the most viable solution available now.  
My project uses Mongo and Mongoose but that shouldn't be a factor if we could enhance the architecture for Fennel.  

My proposal would be to define a repository/model interface that is specifically abstracted from the needs of the Fennel data objects (VCARD, ADDRESSBOOK, GROUP, etc).  It's pretty much there already!  
Replace static `var VCARD = require('../libs/db').VCARD;` with a dependency injection solution 
something like:
`module.exports = function(VCARD){
     return {
        propfind: propfind,
        proppatch: proppatch,
        report: report,
        options: options,
        put: put,
        get: gett,
        delete: del,
        move: move
    };
    // ... rest of method defs 
}`

We'd have to replace sequelize syntax `VCARD.findAndCountAll({ where: {addressbookId: adb.pkey}})` with explicit method definitions like `VCARD.findAndCountAllByAddressbookId(adb.pkey)`
Then move the sequelize code into a default implementation of VCARD
This would allow injecting an alternate data source implementation easily.  
requesthandler.js would load implemented classes via an IoC container or similar.  

The first step would simply be to abstract the sequelize dependency away from the handler classes  and into the db classes.  Then pass the db classes into the handler class import.  The next step is to dynamically load the db class dependency using configuration.  Once this is available, any source can be used for data.  

In my case, I am using Mongo and my app uses Mongoose.  But the world is heading toward GraphQL and I would probably connect my Mongo data repository to this project using GraphQL.  

Thoughts?

**Comment by Extarys** [comment]
Yea sorry I had so much stuff going on I totally forgot about this project.. I really need a way to keep track of all my things.

**Comment by LordEidi** [comment]
@levous, I get your point. But I would probably use the Table Module pattern instead.  The Handler would not call Sequelize directly but ask the Table Module to do its business logic thing. The table module would decide how to get at the data. For the Handler it is completely transparent where the data is coming from.
