### ISSUE TITLE
What is userId in db.js ?

### ISSUE THREAD

**Issue by Extarys** [LordEidi/fennel.js#23]
In [ fennel/libs/db.js / Line 59](https://github.com/LordEidi/fennel/blob/737d4fbd08ee2709eaedca24e0cac4160df7ac83/libs/db.js#L59)

```
var USER_GROUP = sequelize.define('USER_GROUP', {
    userId: { type: Sequelize.STRING, allowNull: false, unique: false, primaryKey: true},
    groupId: { type: Sequelize.STRING, allowNull: false, unique: false, primaryKey: true},
    description: { type: Sequelize.TEXT, allowNull: true}
});
```

The userId is related to... what? I'm not sure if I should link this to a pre-existing user in my database or if it's related to the current schema and a field is misnamed.

EDIT: Prehaps it was supposed to be **ownerId**?

**Comment by LordEidi** [comment]
It's a bit of work in progress and somewhat a hack. It's a "foreign key" into whatever authentication system you use with Fennel. Since users are not necessarily managed within Fennel, it's a hack since we won't be able to set a constraint on that field in the database. Let me explain with an example:

If you authenticate users with Courier, you may have a user user@domain.tld authenticating with Fennel. So that you do not have to write complex rules for all users for simple authorisation checks, I am in the process to introduce groups. Which means that you could make a group "holidays" with users "a", "b" and "d" in it. The table you are referencing is the mapping table between (virtual) users and groups.

Once that group thing is in place, it is possible to write an authorisation rule for Shiro Trie which looks something like this:

`'cal:$group:*'
`

So that every user in group holidays has access to calendar holidays. Until then, that table won't be used.
