### ISSUE TITLE
Opening Up License

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [LordEidi/fennel.js#26]
Hi,
I hope you do not mind me asking, but if you plan not maintain this really, can you open up the license to a little bit more fork friendly one, like Apache 2.0 or MIT?

Kind regards

**Comment by LordEidi** [comment]
Which part of the AGPL is not fork friendly enough?

**Comment by eljefedelrodeodeljefe** [comment]
Forking it to use in commercial applications and then altering it requires publishing the derivative work.

**Comment by LordEidi** [comment]
I guess the word that you are looking for is Freeriding, not Forking.

There is no corporate backing for Fennel whatsoever. Every minute put into Fennel was paid by that contributors own pocket. If you think about using Fennel commercially (and only then you seem to have a problem with the licence), why don't you think about giving something back to the project? Since you profit directly from work from others, that only sounds fair to me.
